services:
  inv_app:
    image: nginx:alpine
    container_name: inv_app
    restart: unless-stopped
    volumes:
      - ./inv_app/public:/usr/share/nginx/html:ro
    networks:
      - scoobydoo

  api:
    image: node:18-alpine
    container_name: inv_app_api
    working_dir: /usr/src/app
    command: ["node", "server.js"]
    volumes:
      - ./inv_app:/usr/src/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - scoobydoo

networks:
  scoobydoo:
    external: true
